development:
  adapter: postgresql
  database: rubyholic_development
  host: localhost
  username: rubyholic
  password: 

test:
  adapter: postgresql
  database: rubyholic_test
  host: localhost
  username: rubyholic
  password:

production:
  adapter: postgresql
  database: rubyholic_production
  host: localhost
  username: zenspider
  password: 
