defaults: &defaults
  adapter: postgresql
  host: localhost
  username: rubyholic
  password: 
  
development:
  database: rubyholic_development
  <<: *defaults

test:
  database: rubyholic_test
  <<: *defaults

production:
  database: rubyholic_production
  username: zenspider
  <<: *defaults
